### ISSUE TITLE
天综合接口的"actPoint": 0没有说明，请问是什么定义？ 

### ISSUE THREAD

**Issue by pjl2008** [Ginshell/bongOpenPlatform#28]
谢谢！

**Comment by crl228** [comment]
你好 这个字段是活跃点，但是现在这个接口的这个字段已经废弃，后续会被剔除。如需使用活跃点相关内容，可以使用活跃点相关的字段

**Comment by pjl2008** [comment]
@crl228 ok，我们猜测也是这个含义。活跃点对于我们用处不大，那我们不考虑就行了。另外如果后续表结构有变化的话能否通过什么方式广播一下，以便于我们的修改。谢谢！

**Comment by crl228** [comment]
这个是我们之前的疏忽，基本现有接口的结构不会发生变化，我们尽量会通过新增的方式来进行处理，如果有较大的变化，会通过邮件的方式进行通知
