### ISSUE TITLE
测试环境用户

### ISSUE THREAD

**Issue by blurrcat** [Ginshell/bongOpenPlatform#31]
要在测试环境创建用户，除了下载“测试环境安装包”，是否有其他途径？例如web? 没有安卓设备。。

**Comment by crl228** [comment]
iOS的会在近期更新，可以先发送一个测试账号供临时使用

**Comment by blurrcat** [comment]
所以即使是web应用接入，我也需要一个移动设备来连接测试环境以创建账号和测试数据？
如果可以直接连接正式环境，这一切都会简单的多
