### ISSUE TITLE
bong的授权必须在bong app的扩展应用里面做吗？

### ISSUE THREAD

**Issue by lydragonarchon** [Ginshell/bongOpenPlatform#34]
比如我开发了一个应用，但并不发布在bong app的扩展应用里，可以吗？bong对这种做法有限制吗？

**Comment by Heyii** [comment]
可以的。我们现在有SDK，可以直接开发使用。

**Comment by pjl2008** [comment]
@Heyii  如果这个应用是web应用呢，它是要发布在“拓展”里，用户使用时候进行授权，还是可以直接在我们的web应用页面里让用户完成这个授权的操作？

**Comment by crl228** [comment]
发布在拓展里是可选项而不是必选项，是否发布在“拓展”里与是否是web应用也没有任何必然关系，可以参考其他开放平台的相关策略。

**Comment by lydragonarchon** [comment]
也就是说可以开发独立应用。那么测试环境和上线环境的区别在哪？上线环境的申请上线只是申请分配新的AppID、AppKey吗？并不是指要上线到拓展里吧？

**Comment by crl228** [comment]
测试环境和生产环境的区别在于：1、测试环境与生产环境完全独立，测试环境能够比较方便的进行调试开发。2、因为数据涉及的用户的个人隐私，在测试环境开发完成后我们需要审核应用是否对用户的隐私造成危害。
对应的id是同一份，申请通过后会切换环境和拓展没有必然关系，希望加入拓展可以单独申请。

**Comment by lydragonarchon** [comment]
谢谢
