### ISSUE TITLE
第三方应用接入

### ISSUE THREAD

**Issue by uusilver** [Ginshell/bongOpenPlatform#35]
我看了下开发文档，对第三方的接入方式描述的不是很清楚。我的理解是，根据开源的SDK，自己打包IOS或者安卓应用，然后提交给平台来获得审核上架？
如果是IOS应用审核，最终是打包成ipa文件，安卓打包成apk文件？
根据appid等验证机制可以来获取数据，那这些获得的数据我是否可以经过web service的包装 发送到我自己的数据库服务器中呢？

**Comment by crl228** [comment]
1、可以选择使用sdk或者使用web API的方式，不论哪种方式，接入bong的生产环境都需要提交上线申请。
2、如果是移动应用（app），Android需要提供apk，iOS需要提供ipa供审核。
3、平台采用oauth2授权，即经过用户授权后可以获取对应用户数据，如何使用与保存需要用户与第三方接入自行考量
