### ISSUE TITLE
请教如何使用bongSDK

### ISSUE THREAD

**Issue by chengliang5** [Ginshell/bongOpenPlatform#37]
Dear Engineer，

我正在用贵司提供的android sdk开发一款app，希望可以通过sdk获取运动步数，消耗能量等信息。但是看sdk的说明文档貌似只能获取到x,y,z坐标。

BongManager.bongStartSensorOutput(sensorUiListener);

         ConnectUiListener sensorUiListener = new ConnectUiListener() {

             @Override

             public void onDataReadInBackground(byte[] data) {

                // data是一个length为3的数组，data[0]为X轴数据，data[1]为Y轴数据，data[3]为Z轴数据。

             }

         };

因此我有三个问题想请教下：

1，请问x,y,z轴坐标是指示运动的轨迹吗？

2，对应坐标值的单位是m, km, 还是经纬度？

3，是否可以转换成步数和消耗的能量以及速率？

期待您的回复！

**Comment by Heyii** [comment]
https://github.com/Ginshell/bongSDK-android
不要使用开启传感器的示例，同步数据即可

**Comment by 1032164662** [comment]
同问，怎么获取数据啊?

**Comment by litesuits** [comment]
不需要开启传感器，通过SDK完成授权，然后调用响应API完成数据的获取。
API文档地址：
https://github.com/Ginshell/bongOpenPlatform

**Comment by chengliang5** [comment]
请问使用sdk如何绑定bong手环，貌似不先绑定手环，无法同步数据！

**Comment by 1032164662** [comment]
请问BongX如何与手机绑定，我在demo和文档中都没有找到相关方法。期待您的回复
