### ISSUE TITLE
如何周期的同步用户的数据

### ISSUE THREAD

**Issue by derekhdy** [Ginshell/bongOpenPlatform#41]
我们的平台要从BongOpenPlatform中来同步数据。目前BongOpenPlatform平台提供的接口是获取某一天或者某些天的运动或者睡眠数据。如果用户好多天没有上传数据，我们如何做数据同步，保证不丢失用户刚刚上传的多天前的数据？
我建议是能不能提供一个接口，按照上传的时间来获取数据，或者提供push的接口BongOpenPlatform来推送数据给第三方平台（Fitbit, Jawbone，都是这种模式）。
请指教！谢谢！

**Comment by crl228** [comment]
1、可以自己记录最后获取数据的时间点来根据时间获取
2、push接口的问题已经在考虑之中

**Comment by derekhdy** [comment]
多谢!
https://github.com/Ginshell/bongOpenPlatform/blob/master/docs/api_sum.md，
这个接口描述的时间是指数据上传的时间吗？还是运动发生的时间？

**Comment by crl228** [comment]
发生日期

**Comment by derekhdy** [comment]
那我如何根据这个日期查找数据，比如用户10天没有上传数据，刚刚上传了一次数据，包含了10天的。现在周期查询的时间触发了，我该如何去查？

**Comment by crl228** [comment]
这种逻辑根据现在提供的接口自己设计下就可以实现
