### ISSUE TITLE
redirect_uri_mismatch错误

### ISSUE THREAD

**Issue by derekhdy** [Ginshell/bongOpenPlatform#43]
测试环境调用接口如下：
http://open-test.bong.cn/oauth/token?code=<获取到的code>&client_id=<我们的clientID>&grant_type=authorization_code&client_secret=<我们的client secret>&redirect_uri=<我们的redirect_rui>

返回
{"error":"redirect_uri_mismatch","error_description":"Redirect URI mismatch."}

我们的client id 是：1430101108761
忘了在注册的时候有没有加上redirect_uri

**Comment by crl228** [comment]
可以参考 #30

**Comment by derekhdy** [comment]
我的redirect_uri写的是：http://www.newreach.cn/nruser/bong/bind
这样有问题吗？
能不能帮我们查查申请时填的redirect_uri是什么？

**Comment by crl228** [comment]
申请时没有备注redirect_uri，默认为空

**Comment by derekhdy** [comment]
那我现在出的错误是什么原因？

**Comment by crl228** [comment]
看上去可能调用/oauth/authorize接口时候和/oauth/token填写的uri不同

**Comment by derekhdy** [comment]
谢谢。你说的对，两个接口的url相差了一个"/"
