### ISSUE TITLE
android测试环境安装包

### ISSUE THREAD

**Issue by kuaileboy1989** [Ginshell/bongOpenPlatform#44]
在bong.cn/share下没有找到测试环境安装包下载的入口，请麻烦提供下链接地址，谢谢，急急急。

**Comment by crl228** [comment]
![_2015-04-29_17_04_07](https://cloud.githubusercontent.com/assets/3185292/7387687/b76f7df4-ee91-11e4-946e-0d5ed061b1c8.png)
或者参考 #42
