### ISSUE TITLE
refresh_token过期了如何处理

### ISSUE THREAD

**Issue by derekhdy** [Ginshell/bongOpenPlatform#45]
Web端接入，refresh_token有过期的时间，如果refresh_token过期怎么处理？让用户重新授权访问？

**Comment by crl228** [comment]
acess_token过期需要使用refresh_token刷新，refresh_token的过期时间一般会分配比较长，但是为了处理方便可以当返回acess_token过期时，直接重新授权。

**Comment by derekhdy** [comment]
两个问题：
1. 当refresh_token过期的时候，只能让用户重新授权了吧？我看refresh_token的过期时间大概是1年
2. "但是为了处理方便可以当返回acess_token过期时，直接重新授权。"  这是什么意思？我不需要使用refresh token来重新获取access token, 平台会自动延长access token?

**Comment by crl228** [comment]
1、是的
2、因为acess_token无效除了过期可能还有其他情况，比如说用户取消授权等，这样做只是为了方便处理。理想方式当然是过期就使用refresh_token处理，一般refresh_token的时间要比access_token长很多

**Comment by crl228** [comment]
1

**Comment by derekhdy** [comment]
谢谢！
