### ISSUE TITLE
请问数据同步的时候，是否可以省略用户触摸yes键这个步骤？

### ISSUE THREAD

**Issue by duiduilove** [Ginshell/bongOpenPlatform#48]
RT，我在做一个健康类的应用，希望打开app的时候自动去同步手环的计步睡眠数据。同步的时候用户不需要触摸一下yes键，直接同步过来。是否可以？

**Comment by crl228** [comment]
你好，bong II不支持，bong X与bong XX可以支持

**Comment by duiduilove** [comment]
Thanks！
