### ISSUE TITLE
请求 request_token 时返回字符串为空，是什么原因

### ISSUE THREAD

**Issue by dtislife** [Ginshell/bongOpenPlatform#51]

**Comment by crl228** [comment]
具体请求的url形式是？

**Comment by dtislife** [comment]
http://open-test.bong.cn/oauth/authorize?client_id=1431401070709&response_type=code

**Comment by dtislife** [comment]
@crl228 http://open-test.bong.cn/oauth/authorize?client_id=1431401070709&response_type=code，是这个地址，麻烦帮忙看下，谢谢！

**Comment by crl228** [comment]
没填回调地址，请参考文档

**Comment by dtislife** [comment]
@crl228 申请开发权限的时候有填，而且我试过加回调地址也是不行。http://open-test.bong.cn/oauth/authorize?client_id=1431401070709&redirect_uri=http://www.jiazi-it.com/yanshi/index.php&response_type=code

**Comment by crl228** [comment]
1、回调地址一般在开发的时候可能会经常变，默认不会添加，如果需要添加请发送邮件到long@bong.cn说明。
2、我试下这个地址，是可以拿到code的
![2015-05-13 14 12 39](https://cloud.githubusercontent.com/assets/3185292/7604749/fd8b12ec-f979-11e4-9254-0aeb727241a9.png)

**Comment by dtislife** [comment]
好的，谢谢！
