### ISSUE TITLE
我无法注册测试环境的账户

### ISSUE THREAD

**Issue by chenshuyang83123** [Ginshell/bongOpenPlatform#86]
我下载了 <Android APK 测试环境稳定版本> 并且安装在我的安卓手机上面。
我用手机号码来注册新帐户的时候，提示 “该号码已被注册” 并且我没有收到任何短信验证码。
可是当我试图通过登陆画面的忘记密码功能来找回密码的时候，又提示我 "该用户未被注册"

请问测试环境的账户是如何注册的，是通过邮件和 “sdkopen@bong.cn” 申请么？

**Comment by crl228** [comment]
你好，麻烦把你的手机号发送邮件至 long@bong.cn

**Comment by chenshuyang83123** [comment]
你好我的手机是 135-9174-3080
Date: Sun, 1 Nov 2015 21:39:33 -0800

**Comment by crl228** [comment]
你好 我确认下，线上环境这个号8月份已注册，测试环境没有，是不是两个环境搞混了

**Comment by chenshuyang83123** [comment]
这个号码我确实用在生产环境了，不过为什么不能登陆测试环境呢？
我用的测试环境apk 是这个 “Android APK 测试环境稳定版本”
刚刚通过 https://github.com/Ginshell/bongSDK-android 来下载的。

请问是否需要我再提供一个其他的手机号码？

我现在想做的事情就是通过测试环境apk 绑定一个手环，
然后上传一些运动数据，
然后想通过android sdk 里面的demo 来认证授权我的测试环境用户，
并且通过同步功能来获取我在测试环境上面的运动数据。

**Comment by chenshuyang83123** [comment]
你好
我的另外一个手机号码186-4094-6236
这个号码没有在Bong任何环境注册过不过还是不能用来注册测试环境的账户我使用的apk 是 bong_test_env.apk刚刚从这个页面下载的https://github.com/Ginshell/bongSDK-android我下载的时候选择的是稳定版本
多谢回复


From: chenshuyang.cn@outlook.com
To: long@bong.cn
CC: reply@reply.github.com
Subject: RE: [bongOpenPlatform] 我无法注册测试环境的账户 (#86)
Date: Mon, 2 Nov 2015 05:43:50 +0000




你好我的手机是 135-9174-3080
Date: Sun, 1 Nov 2015 21:39:33 -0800

**Comment by crl228** [comment]
https://github.com/Ginshell/bongOpenPlatform/blob/master/apk/bongT_3_0_3_0.apk,这个是测试app，测试环境和生产环境是隔离的，可以同时注册使用。其他的问题我看下是不是由于我们在调试导致的，可以把另一个手机号也一并提供下，谢谢

**Comment by chenshuyang83123** [comment]
另一个号码也邮件交给你了。

我刚才下载了
https://github.com/Ginshell/bongOpenPlatform/blob/master/apk/bongT_3_0_3_0.apk

仍然是一样的问题，
我注册发送验证码的画面
不论我输入任何手机号码，
都提示 “该手机号已被注册”
而且我没有收到验证短信

**Comment by crl228** [comment]
你好 已确认测试环境刚在进行调试开发，现在已恢复，对造成的困扰深感抱歉

**Comment by chenshuyang83123** [comment]
可以了
多谢多谢
