### ISSUE TITLE
为什么有些API在访问时会出现“JsonParseException”错误呢？

### ISSUE THREAD

**Issue by chenshuyang83123** [Ginshell/bongOpenPlatform#87]
你好

我在使用sdk demo 程序进行授权成功后取得了uid 和 access_token
为了不泄露真正的Token，我下问假设取到的数据是这样的
uid: 12345678901234567890
access_token: abcd1234-1234-1234-1234-abcd12345678

当我测试用户资料信息的时候，
按照文档中描述使用如下的url
http://open-test.bong.cn/1/userInfo/12345678901234567890?access_token=abcd1234-1234-1234-1234-abcd12345678
访问成功并且返回正确的数据

可是我测试天详细数据接口的时候，
使用下面的url
http://open-test.bong.cn/1/bongday/blocks/20151102?uid=12345678901234567890&access_token=abcd1234-1234-1234-1234-abcd12345678
却返回 HTTP 500 错误

下面是一部分错误的消息
HTTP ERROR 500
Problem accessing /1/bongday/blocks/20151102. Reason:
  Server Error
  Caused by:
   org.codehaus.jackson.JsonParseException: Illegal character '-' (code 0x2d) in base64 content  at [Source: N/A; line: -1, column: -1]
	at org.codehaus.jackson.node.TextNode._reportInvalidBase64(TextNode.java:291)

请问这是什么原因造成的呢？

**Comment by crl228** [comment]
你好 测试服务器调试中  这周末前会修复

**Comment by chenshuyang83123** [comment]
已经解决了。
谢谢啦。
感谢回复。
