### ISSUE TITLE
天详细的 API 接口调用失败

### ISSUE THREAD

**Issue by chenshuyang83123** [Ginshell/bongOpenPlatform#88]
你好

我在授权成功后拿到了 access_token 和 uid
但是唯独在调用 天详细 API 接口的时候返回 服务器错误 Error 500
org.codehaus.jackson.JsonParseException: Illegal character '-' (code 0x2d) in base64 content
 at [Source: N/A; line: -1, column: -1]

我的请求是 
http://open-test.bong.cn/1/bongday/blocks/20151104?uid=73863268712343424943&access_token=3bc693fc-8820-41c9-97a4-911e3abc6e64

我觉得 access_token 和 uid 是没有问题的，
因为其他接口访问都可以正常取得Json数据

多谢

**Comment by chenshuyang83123** [comment]
我发现只要把/blocks/后面的 日期换成 没有上传过数据的日期就不会出现这个错误，
但是返回的Json并不是
https://github.com/Ginshell/bongOpenPlatform/blob/master/docs/api_bongday.md
中的格式。

**Comment by chenshuyang83123** [comment]
没人关注么？

**Comment by crl228** [comment]
你好 由于测试环境在调试jackson的版本导致 现在已经调试完毕

**Comment by chenshuyang83123** [comment]
已经可以用了，多谢多谢。
